In [13]:
#reverse the array
import numpy as np

def arrays(arr):
    res = np.array(arr,float)  
    res = res[::-1]
    return res
arr = input().strip().split(' ')
res = arrays(arr)
print(res)


 1 5 6


[6. 5. 1.]


In [17]:
#reshape the array

import numpy
arr = input().strip().split(' ')
my_array = numpy.array(arr,int)
print(numpy.reshape(my_array,(3,3)))


 1 2 3 4 5 6 7 8 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
## Transpose and flatten

#The first line contains the space separated values of N and M.
#The next  lines contains the space separated elements of  columns.

import numpy
m,n = input().strip().split(' ')
arr = []

for i in range(int(m)):
        ele = list(map(int,input().split(' ')))
        arr.append(ele)
arr = numpy.array(arr)
print(arr.transpose())
print(arr.flatten())

 2 3
 1 2 3
 4 5 6


[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]


In [29]:
# Array concatenation


import numpy
m,n ,p = input().strip().split(' ')
arr1 = []
for i in range(int(m)):
        ele = list(map(int,input().split(' ')))
        arr1.append(ele)
arr1 = numpy.array(arr1)
arr2 = []
for i in range(int(n)):
        ele = list(map(int,input().split(' ')))
        arr2.append(ele)
arr2 = numpy.array(arr2)
print(numpy.concatenate((arr1,arr2),axis=0))

 4 3 2
 1 2
 3 2
 3 4
 2 3
 1 2
 3 2
 3 4


[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [36]:
# zeros and ones

import numpy

ele = list(map(int, input().split(' ')))
print(np.zeros((ele),int))
print(np.ones((ele),int))


 2 3


[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [44]:
#Identity and eye

import numpy
numpy.set_printoptions(legacy='1.13')
n, m = map(int, input().split())
print(numpy.eye(n,m))

None


 2 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]]


Add ( + )
Subtract ( - )
Multiply ( * )
Integer Division ( / )
Mod ( % )
Power ( ** )


In [49]:
import numpy
m,n  = input().strip().split(' ')
arr1 = []
for i in range(int(m)):
        ele = list(map(int,input().split(' ')))
        arr1.append(ele)
arr1 = numpy.array(arr1)
arr2 = []
for i in range(int(m)):
        ele = list(map(int,input().split(' ')))
        arr2.append(ele)
arr2 = numpy.array(arr2)
print(numpy.add(arr1,arr2))
print(numpy.subtract(arr1,arr2))
print(numpy.multiply(arr1,arr2))
print(numpy.floor_divide(arr1,arr2))
print(numpy.mod(arr1,arr2))
print(numpy.power(arr1,arr2))

 1 4
 1 2 3 4
 2 3 4 5


[[3 5 7 9]]
[[-1 -1 -1 -1]]
[[ 2  6 12 20]]
[[0 0 0 0]]
[[1 2 3 4]]
[[   1    8   81 1024]]


In [56]:
#Floor, ceil, rint
import numpy
numpy.set_printoptions(legacy='1.13')
ele  = list(map(float,input().strip().split(' ')))
arr  = numpy.array(ele)
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

 1 2 3 4 5


[ 1.  2.  3.  4.  5.]
[ 1.  2.  3.  4.  5.]
[ 1.  2.  3.  4.  5.]


In [58]:
# sum and prod
import numpy
m,n  = input().strip().split(' ')
arr1 = []
for i in range(int(m)):
        ele = list(map(int,input().split(' ')))
        arr1.append(ele)
arr1 = numpy.array(arr1)
arr_sum = numpy.sum(arr1,axis=0)
arr_prod = numpy.prod(arr_sum)
print(arr_prod)



 2 2 
 1 2
 3 4


24


In [59]:
#min and max
import numpy
m,n  = input().strip().split(' ')
arr1 = []
for i in range(int(m)):
        ele = list(map(int,input().split(' ')))
        arr1.append(ele)
arr1 = numpy.array(arr1)
arr_min = numpy.min(arr1,axis=1)
arr_max = numpy.max(arr_min)
print(arr_max)


 2 2
 1 2
 3 4


3


In [61]:
#mean, var, std
import numpy
m,n  = input().strip().split(' ')
arr1 = []
for i in range(int(m)):
        ele = list(map(int,input().split(' ')))
        arr1.append(ele)
arr1 = numpy.array(arr1)
arr_mean = numpy.mean(arr1,axis=1)
arr_var = numpy.var(arr1,axis=0)
arr_std = numpy.round(numpy.std(arr1,axis=None),11)

print(arr_mean)
print(arr_var)
print(arr_std)


 2 2
 1 2
 3 4


[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [66]:
import numpy
m  = input().strip().split(' ')
arr1 = []
for i in range(int(m[0])):
        ele = list(map(int,input().split(' ')))
        arr1.append(ele)
arr1 = numpy.array(arr1)
arr2 = []
for i in range(int(m[0])):
        ele = list(map(int,input().split(' ')))
        arr2.append(ele)
arr2 = numpy.array(arr2)
print(numpy.dot(arr1,arr2))

 2
 1 2
 2 3
 1 2
 2 3


[[ 5  8]
 [ 8 13]]


In [ ]:
#inner and outer
import numpy
#numpy.set_printoptions(legacy='1.13')
ele  = list(map(int,input().strip().split(' ')))
arr1  = numpy.array(ele)
ele1  = list(map(int,input().strip().split(' ')))
arr2  = numpy.array(ele1)
print(numpy.inner(arr1,arr2))
print(numpy.outer(arr1,arr2))

In [68]:
#polynomial
import numpy
#numpy.set_printoptions(legacy='1.13')
ele  = list(map(float,input().strip().split(' ')))
arr1  = numpy.array(ele)
ele1  = int(input())
print(numpy.polyval(arr1,ele1))

 1.1 2 3
 0


3.0


In [70]:
import numpy
m  = input().strip().split(' ')
arr1 = []
for i in range(int(m[0])):
        ele = list(map(float,input().split(' ')))
        arr1.append(ele)
arr1 = numpy.array(arr1)
print(numpy.linalg.det(arr1))

 2
 1.1 1.1
 1.1 1.2


0.11


In [72]:
import numpy
m  = input().strip().split(' ')
arr1 = []
for i in range(int(m[0])):
        ele = list(map(float,input().split(' ')))
        arr1.append(ele)
arr1 = numpy.array(arr1)
print(numpy.round(numpy.linalg.det(arr1),2))

 2
 1.1 1.1
 1.1 1.2


0.11
